title: "Rodrigo Jazinski"
description: "Arquiteto de Sistemas e CTO | Coach Executivo | Pesquisador Independente em Sistemas Simbólicos"
markdown: kramdown

theme: null
show_downloads: false

github:
  is_project_page: false
